{
	"version": 1476311519,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/standardiso-sheet0.png",
		"images/character-sheet0.png",
		"images/largeiso-sheet0.png",
		"images/pellet-sheet0.png",
		"images/particles.png",
		"images/follow-sheet0.png",
		"images/trail-sheet0.png",
		"images/tiledbackground.png",
		"images/bg_cube-sheet0.png",
		"images/nebulabg.png",
		"images/sprite-sheet0.png",
		"media/click1.m4a",
		"media/click1.ogg",
		"media/click2.m4a",
		"media/click2.ogg",
		"media/collect.m4a",
		"media/collect.ogg",
		"media/collect2.m4a",
		"media/collect2.ogg",
		"media/sweep sfx 26.m4a",
		"media/sweep sfx 26.ogg",
		"media/bg_theme.m4a",
		"media/bg_theme.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}